language: bash

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

before_install:
 - 'if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.4/cmake-3.4.3-Linux-x86_64.tar.gz";
      mkdir cmake && travis_retry curl -s ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake || travis_terminate 1;
      export PATH=${PWD}/cmake/bin:${PATH} || travis_terminate 1;
      echo $PATH
    else
      brew install cmake || travis_terminate 1;
    fi'

before_script:
 - ./install.sh && source ~/.llvmvm/scripts/llvmvm.sh
 - cmake --version

script:
 - llvmvm install release_391_final
