language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: true
    - os: osx
      osx_image: xcode7.3

before_install:
  - 'if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.4/cmake-3.4.3-Linux-x86_64.tar.gz";
      mkdir cmake && travis_retry curl -s ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake || travis_terminate 1;
      export PATH=${PWD}/cmake/bin:${PATH} || travis_terminate 1;
    fi'
  - cmake --version


before_script:
 - binscripts/llvmvm-installer
 - source ~/.llvmvm/scripts/llvmvm.sh
 - which tr

script:
 - llvmvm list
 - llvmvm help
 - llvmvm listalltags
 - llvmvm listallbins
 - echo $PATH
 - llvmvm install 3.2-x86_64-linux-ubuntu-12.04 -B
 - ls $HOME/.llvmvm/llvms
 - echo $PATH
 - llvmvm use 3.2-x86_64-linux-ubuntu-12.04
 - llvmvm use 3.2-x86_64-linux-ubuntu-12.04 --default
 - echo $PATH
 - 'if [[ ! `which llc` == *".llvmvm"* ]]; then
      echo `which llc`;
      travis_terminate 1;
    fi'
 - llvmvm uninstall 3.2-x86_64-linux-ubuntu-12.04
 - 'if [[ `which llc` == *".llvmvm"* ]]; then
      echo `which llc`;
      travis_terminate 1;
    fi'
 - llvmvm list
 - llvmvm install 3.2-x86_64-linux-ubuntu-12.04 -B -n linux-3.2
 - llvmvm use linux-3.2 --default
 - echo $PATH
 - 'if [[ ! `which llc` == *".llvmvm"* ]]; then
      echo `which llc`;
      travis_terminate 1;
    fi'

