#!/usr/bin/env bash

# This file taken almost whole-hog from gvm


display_error() {
	tput sgr0
	tput setaf 1
	echo "ERROR: $1"
	tput sgr0
	exit 1
}

update_profile() {
	[ -f "$1" ] || return 1

	grep -F "$source_line" "$1" > /dev/null 2>&1
	if [ $? -ne 0 ]; then
		echo -e "\n$source_line" >> "$1"
	fi
}

BRANCH=${1:-master}
LLVMVM_DEST=${2:-$HOME}
LLVMVM_NAME="llvmvm"
SRC_REPO=${SRC_REPO:-https://github.com/cwpearson/llvmvm.git}

[ "$LLVMVM_DEST" = "$HOME" ] && LLVMVM_NAME=".llvmvm"

[ -d "$LLVMVM_DEST/$LLVMVM_NAME" ] && display_error "Already installed!"
[ -d "$LLVMVM_DEST" ] || mkdir -p "$LLVMVM_DEST" > /dev/null 2>&1 || display_error "Failed to create $LLVMVM_DEST"
[ -z "$(which git)" ] && display_error "Could not find git"

# Is llvmvm-installer being called from the origin repo?
# If so, skip the clone and source locally!
# This prevents CI from breaking on non-merge commits.

GIT_ROOT=$(git rev-parse --show-toplevel 2>/dev/null)

if [[ -z "$GIT_ROOT" || "$(basename "$GIT_ROOT")" != "llvmvm" ]]
then
  echo "Cloning from $SRC_REPO to $LLVMVM_DEST/$LLVMVM_NAME"

  git clone --quiet "$SRC_REPO" "$LLVMVM_DEST/$LLVMVM_NAME" 2> /dev/null ||
	  display_error "Failed to clone from $SRC_REPO into $LLVMVM_DEST/$LLVMVM_NAME"
else
  if [[ $LLVMVM_DEST == *"$GIT_ROOT"* ]]
  then
    ln -s "$GIT_ROOT" "$LLVMVM_DEST"
  else
    cp -r "$GIT_ROOT" "$LLVMVM_DEST/$LLVMVM_NAME"
  fi
fi