#!/usr/bin/env bash

# This file taken almost whole-hog from gvm


display_error() {
	tput sgr0
	tput setaf 1
	echo "ERROR: $1"
	tput sgr0
	exit 1
}

update_profile() {
	[ -f "$1" ] || return 1

	grep -F "$source_line" "$1" > /dev/null 2>&1
	if [ $? -ne 0 ]; then
		echo -e "\n$source_line" >> "$1"
	fi
}

BRANCH=${1:-master}
LLVMVM_DEST=${2:-$HOME}
LLVMVM_NAME="llvmvm"
SRC_REPO=${SRC_REPO:-https://github.com/cwpearson/llvmvm.git}

[ "$LLVMVM_DEST" = "$HOME" ] && LLVMVM_NAME=".llvmvm"

[ -d "$LLVMVM_DEST/$LLVMVM_NAME" ] && display_error "Already installed!"
[ -d "$LLVMVM_DEST" ] || mkdir -p "$LLVMVM_DEST" > /dev/null 2>&1 || display_error "Failed to create $LLVMVM_DEST"
[ -z "$(which git)" ] && display_error "Could not find git"

# Is llvmvm-installer being called from the origin repo?
# If so, skip the clone and source locally!
# This prevents CI from breaking on non-merge commits.

GIT_ROOT=$(git rev-parse --show-toplevel 2>/dev/null)

if [[ -z "$GIT_ROOT" || "$(basename "$GIT_ROOT")" != "llvmvm" ]]
then
  echo "Cloning from $SRC_REPO to $LLVMVM_DEST/$LLVMVM_NAME"

  git clone --quiet "$SRC_REPO" "$LLVMVM_DEST/$LLVMVM_NAME" 2> /dev/null ||
	  display_error "Failed to clone from $SRC_REPO into $LLVMVM_DEST/$LLVMVM_NAME"
else
  if [[ $LLVMVM_DEST == *"$GIT_ROOT"* ]]
  then
	  echo "Linking $GIT_ROOT to $LLVMVM_DEST"
    ln -s "$GIT_ROOT" "$LLVMVM_DEST"
  else
	  echo "Copying $GIT_ROOT to $LLVMVM_DEST/$LLVMVM_NAME"
    cp -r "$GIT_ROOT" "$LLVMVM_DEST/$LLVMVM_NAME"
  fi
fi

# Add line to source llvmvm to the shell
source_line="[[ -s \"${LLVMVM_DEST}/$LLVMVM_NAME/scripts/llvmvm.sh\" ]] && source \"${LLVMVM_DEST}/$LLVMVM_NAME/scripts/llvmvm.sh\""
source_file="${LLVMVM_DEST}/$LLVMVM_NAME/scripts/llvmvm.sh"

if [ -z "$LLVMVM_NO_UPDATE_PROFILE" ] ; then
  if [ -n "$ZSH_NAME" ]; then
    update_profile "$HOME/.zshrc"
  elif [ "$(uname)" == "Linux" ]; then
    update_profile "$HOME/.bashrc" || update_profile "$HOME/.bash_profile"
  elif [ "$(uname)" == "Darwin" ]; then
    update_profile "$HOME/.profile" || update_profile "$HOME/.bash_profile"
  fi
fi

if [ -z "$GVM_NO_UPDATE_PROFILE" ] && [ "$?" != "0" ]; then
	echo "Unable to locate profile settings file(Something like $HOME/.bashrc or $HOME/.bash_profile)"
	echo
	echo " You will have to manually add the following line:"
	echo
	echo "  $source_line"
	echo
fi

echo "export LLVMVM_ROOT=$LLVMVM_DEST/$LLVMVM_NAME" > "$LLVMVM_DEST/$LLVMVM_NAME/scripts/llvmvm.sh"
echo ". \$LLVMVM_ROOT/scripts/llvmvm-base.sh" >> "$LLVMVM_DEST/$LLVMVM_NAME/scripts/llvmvm.sh"
[[ -s "$LLVMVM_DEST/$LLVMVM_NAME/scripts/llvmvm.sh" ]] && source "$LLVMVM_DEST/$LLVMVM_NAME/scripts/llvmvm.sh"
echo "Installed LLVMVM"
echo
echo "Please restart your terminal session or to get started right away run"
echo " \`source ${source_file}\`"
echo